### ISSUE TITLE
Unclear use cases and example for photo gallery navigation queuing

### ISSUE THREAD

**Issue by esprehn** [WICG/app-history#10]
https://github.com/WICG/app-history/blob/main/README.md#queued-up-single-page-navigations

Perhaps this is just unclear in the explainer, but if each click does pushNewEntry, and future ones don't run until the previous is finished with respondWith(), then does that mean there's a queue of [ push(1), push(2), push(3), ... push(N) ]? So if there's a 100ms animation, and I click next 20 times, it'll take 2 seconds to reach the right photo?

In a real application I think we'd probably want to skip ahead if you clicked Next many times or decrease the animation duration, instead of running all the animations for each one, but there's no way to know that the queue has become super deep to skip head from what I see in the API? Is it expected that consumers will build their own queue on the side to keep track of pending navigations?

It also took me a second to realize that the expected behavior is that the "Next" link has an anchor that points to the wrong photo number during a queued transition. So if you tap Next 10 times, and then on the 11th Shift+Click Next you'll open photo 2 in a new tab, not photo 11. I suppose maybe that is expected behavior, but that's kind of subtle. Is there precedent for either behavior on the web or native apps?

**Comment by tbondwilkinson** [comment]
I think that applications should definitely do debouncing on the UI element itself.

If clicking some UI element triggers an expensive operation (like an animation, or a server fetch), you shouldn't allow clicking on it until you're sure that a previous expensive operation.

To make the navigation framework handle what are essentially bad inputs seems to me not the business of the framework

**Comment by esprehn** [comment]
I don't think these are bad inputs. It's very common to allow someone to click Next rapidly in a photo gallery.

**Comment by tbondwilkinson** [comment]
I think this is also related your other issue #13 - the broader question being "how much should the browser framework do automatically with discarding queued navigations"?

But about this specific use case, I think it's pretty tough to know from a framework perspective how to deal with queued navigations, and it's definitely an application decision whether new navigations should preempt existing ones, whether they should be deferred until after the current one finishes, or whether they should be thrown away altogether. I think that choice really depends on what the currently running navigation is.
