### ISSUE TITLE
Should app history care about "allowed to navigate"?

### ISSUE THREAD

**Issue by domenic** [WICG/app-history#110]
Spinning off from #109:

`appHistory.navigate()` is currently specified to not respect HTML's ["allowed to navigate"](https://html.spec.whatwg.org/#allowed-to-navigate) check. This check is what prevents sandboxed iframes from navigating their parents.

However, `appHistory` is not accessible across origins (whereas `location.href` is). So this check only comes into play if you have used `sandbox="allow-scripts allow-same-origin"`. In that case, you can't really prevent the sandboxed iframe from navigating you:  see one easy workaround using `parent.eval()` at https://boom-bath.glitch.me/sandboxed-allowed-to-navigate.html . In general with the `allow-scripts allow-same-origin` combination, all bets are off.

So we have two paths here:

- Behave like `location.pathname`, which is not accessible cross-origin, but has a speed-bump "allowed to navigate" check anyway that means `sandbox="allow-scripts allow-same-origin"` still blocks direct usage to it.
- Omit the "allowed to navigate" check and instead rely on the fact that `appHistory` is not accessible cross-origin.

Another interesting case is `appHistory.back()` and its antecedant `history.back()`. These APIs are a bit more interesting because they do not require `allow-same-origin` to have an effect; they operate on the joint session history, so calling them inside an iframe can navigate the parent. The HTML spec [does include an "allowed to navigate" check](https://html.spec.whatwg.org/#traverse-the-history-by-a-delta) on `history.back()`, which [appears to be](https://boom-bath.glitch.me/sandboxed-allowed-to-navigate.html) implemented in Chrome (without a console message though) and unimplemented in Firefox.

`appHistory.back()` however is a bit different. It will only work if your current frame has a previous entry it can traverse to. So "allowed to navigate" will always return true for such navigations (because they always navigate your frame). So, "allowed to navigate" isn't relevant for `appHistory.back()`.

**Comment by jakearchibald** [comment]
What if going back navigates multiple frames, and one of them is outside the sandbox?

**Comment by domenic** [comment]
Hmm, given that going back with app history can only navigate inclusive-descendant frames, I can't see how that would happen?

**Comment by jakearchibald** [comment]
I thought it obeyed the history timeline?

As in:

1. Sandboxed iframe 1 navigates from foo to bar
1. iframe 2 navigates from hello to world

If iframe 1 navigates back to foo, it needs to navigate iframe 2 too, or diverge from the history timeline.

**Comment by domenic** [comment]
Ah, yep, you're totally right, I drew out one of those timeline diagrams and I see the problem now. OK, so I think we do need the "allowed to navigate" check, at least in `appHistory.back()` and other traversal methods. Which makes me inclined to include it for `appHistory.navigate()` too, even if it's just a speed-bump.

**Comment by jakearchibald** [comment]
Fwiw, my PR will handle this for traversal cases. Actions that modify the history timeline will need to perform the check in advance, if failure should avoid changing the timeline (which is the case for all navigations I think).

However, I think we'll be able to abstract a lot of that, especially for async cases.

**Comment by domenic** [comment]
> Which makes me inclined to include it for appHistory.navigate() too, even if it's just a speed-bump.

After thinking about this over the weekend, I'm no longer inclined to include this, because it'd require relying on the deprecated incumbent concept. `appHistory.navigate()` sets both the source and to-be-navigated browsing contexts equal to the relevant global object's browsing context. If we wanted a check similar to `location.href` we'd need to, similar to `location.href`, set the source browsing context to the incumbent global object's browsing context.

For `appHistory.back()` and friends though, the to-be-navigated browsing context(s) may differ from the relevant global object's browsing context. So those could fail.

(Today, `history.back()` and friends only consider a single to-be-navigated browsing context. I think part of @jakearchibald's work is to make sure we check all of the to-be-navigated browsing contexts?)

**Comment by domenic** [comment]
I'll consider this settled, although speccing it for traversal is hard (because speccing traversal is hard).

**Comment by domenic** [comment]
It looks like I got this wrong. "Allowed to navigate" seems to have to do with sandboxing protections, which could potentially be in place even with `sandbox="same-origin allow-scripts"`. So we need to add a check to navigate().

**Comment by domenic** [comment]
No, I got this right in the first place. A given browsing context is always allowed to navigate itself; sandboxing does not prevent that.
