### ISSUE TITLE
Need timestamp from the initiation of the navigation, not the navigation event

### ISSUE THREAD

**Issue by esprehn** [WICG/app-history#12]
For reporting user interaction metrics we need the start of the user action, not the start of the navigation.

For example if a user clicks the Next button 10 times rapidly (per the photo gallery example), the `navigate` event for the 10th won't fire until all the previous 9 navigations and respondWith()'s have completed. That makes the start time stamp very low by comparison to the user perceived time to get to that destination, which is "Click 10th time" until "URL Change".

I'm not sure the use case for currently defined "navigation event start time" given the arbitrarily long start delay before it's recorded.

**Comment by tbondwilkinson** [comment]
I suspect that we should start counting from the time the appHistory API is called.

Domenic is this already done? Mark as closed?

**Comment by domenic** [comment]
This is being worked in #27, which is not yet merged due to outstanding questions.
