### ISSUE TITLE
canGoBack/canGoForward misleading name

### ISSUE THREAD

**Issue by tbondwilkinson** [WICG/app-history#152]
Are these properties only for same origin, same document back/forward? Because that makes them somewhat misleading. Maybe we can add a noun in there?

canGoBackInDocument?

A little wordy though...

**Comment by domenic** [comment]
No, they're for whether the `back()` or `forward()` methods work. That's same-origin but any-document.

**Comment by domenic** [comment]
Closing since I think this is OK, but let me know if there's still something confusing!
