### ISSUE TITLE
spitballing/questions

### ISSUE THREAD

**Issue by chris-kruining** [WICG/app-history#160]
I really like where this API is going, and it made me think. I have build a visual page editor for my CMS, but I had to write my own crappy implementation of a mutation history. this gives me undo&redo capabilities.

Do you recon I could leverage this API to replace my version of a mutation history?

**Comment by chris-kruining** [comment]
well, the browser nav would not be used, I was thinking of utilizing an invisible iframe

**Comment by domenic** [comment]
I think creating invisible iframes so that you can use their history as something not representing navigation history, but instead some other type of list of states, is not a great idea...
