### ISSUE TITLE
Support for document history?

### ISSUE THREAD

**Issue by bahrus** [WICG/app-history#184]
Is it considered out of scope for appHistory to be used for functionality beyond "page navigation"?

For example, think about VSCode and its ability to reverse changes made to the documents being edited.  Maybe that's an extreme, but other scenarios might be things like adding a widget into a view, expanding a tree.

What I guess I would like to see is an ability to push "micro" changes to the history, that can programmatically be traversed via user supplied buttons or keystrokes, but all those micro changes are grouped together when it comes to clicking the back/forward buttons.

**Comment by bathos** [comment]
A similar interest was expressed in this prior issue: https://github.com/WICG/app-history/issues/160

**Comment by domenic** [comment]
Yeah, as noted there, this is not in scope :). Perhaps another reason for the naming discussion in #83 to trend toward something navigation-related...
