### ISSUE TITLE
appHistory.current.state mention instead of getState usage

### ISSUE THREAD

**Issue by fabiancook** [WICG/app-history#193]
https://github.com/WICG/app-history/blob/7c0332b30746b14863f717404402bc49e497a2b2/README.md?plain=1#L840

In the readme the following code is used:

```typescript
appHistory.updateCurrent({
  state: { ...appHistory.current.state, detailsOpen: detailsEl.open }
});
```

This appears to be the only reference of `.state` on an entry, `.getState()` should be used in place here:

```
appHistory.updateCurrent({
  state: { ...appHistory.current.getState(), detailsOpen: detailsEl.open }
});
```

`detailsOpen` could also be updated directly from the existing state if `open` doesn't exist on the element (if there is some custom implementation of details for example):

```
const state = appHistory.current.getState();
appHistory.updateCurrent({
    state: {
        ...state,
        detailsOpen: detailsElement.open ?? !state?.detailsOpen
    }
})
```

**Comment by domenic** [comment]
Thanks!
