### ISSUE TITLE
Polyfilling performance

### ISSUE THREAD

**Issue by fabiancook** [WICG/app-history#195]
The documented usage of the performance API shows that eventually a new entry type of `"same-document-navigation"`

```typescript
for (const entry of performance.getEntriesByType("same-document-navigation")) {
  console.log(`It took ${entry.duration} ms to navigate to the URL ${entry.name}`);
}
```

However the supported entry types are frozen by the platform 
https://w3c.github.io/performance-timeline/#supportedentrytypes-attribute  meaning that we cannot directly polyfill this. 

I can't see any issues directly talking about the performance entry type. 

In [this implementation](https://github.com/virtualstate/app-history) I have utilised [`performance.mark`](https://github.com/virtualstate/app-history/blob/53ac427f9fcd58cd8d2cbeae2418a3e2a62415ea/src/app-history.ts#L249-L251) + [`performance.measure`](https://github.com/virtualstate/app-history/blob/53ac427f9fcd58cd8d2cbeae2418a3e2a62415ea/src/app-history.ts#L397-L404) from the user land performance API as an alternative, e.g: 

```typescript
try {
        if (entry.sameDocument && typeof navigationType === "string") {
            performance.mark(`same-document-navigation:${entry.id}`);
        }
        /* do transition here */
} finally {
        if (entry.sameDocument && typeof navigationType === "string") {
                performance.mark(`same-document-navigation-finish:${entry.id}`);
                performance.measure(
                    `same-document-navigation:${entry.url}`,
                    `same-document-navigation:${entry.id}`,
                    `same-document-navigation-finish:${entry.id}`
                );
            }
}     
```

Will `"same-document-navigation"` be an entry type available at some point for users to invoke? I am guessing not so, and by then we would have a full app history implementation available alongside.. However this also applies to other environments like [Node.js](https://nodejs.org/api/perf_hooks.html#performancemarkname-options) or [Deno](https://doc.deno.land/deno/stable/~/Performance#mark)

Effectively for all other platforms other than a browser (browser with a native app history implementation) will need to utilise `"measure"`:

```typescript
const entries = performance.getEntriesByType("measure").filter(({ name }) => name.startsWith("same-document-navigation"));
for (const entry of entries) {
  console.log(`It took ${entry.duration} ms to navigate to the URL ${getUrlFromPerformanceEntryName(entry.name)}`);
}
```

**Comment by domenic** [comment]
Yeah, I think this is generally the case when introducing new performance entries; the polyfill won't be able to have 100% fidelity until it's implemented. The intent is for us to follow the same pattern as all new types of performance entries, and not do anything different.

**Comment by fabiancook** [comment]
Okay that makes sense, as long as entries are available, thats minimum viable, and then as they get the real implementation, they will have the correct entry type.
