### ISSUE TITLE
Compatibility & Impact of `navigate` on non-history based routing

### ISSUE THREAD

**Issue by mmocny** [WICG/app-history#22]
Framework level Routers today support saving route state in different ways: via history api, hash fragment, in-memory, and potentially other storage mechanisms.  I don't fully grasp the uses for these alreative routers (is it just for tests and other non-web contexts?)

Regardless of the method, I believe most user initiated route changes tend to follow the same process: intercept user interactions, update route, then update view according to new route.

With the introduction of the `navigate` event and the ability to preventDefault action of `<a>` directly, history based routers can become implemented a new way, without intercepting the interaction first.  However, it seems this may not be easily extended to the other forms of routing, since I think fundamentally `navigate` event relies on a history change to kick things off.

While this is fine, does it pose compatibility and incentives issues?

For example, would a future experimental React Router need `<Link>` to conditionally use click interception if and only if the nested `<Router>`  was not an `ExperimentalNavigateBrowserRouter`?

(Not an expert on client routers, just thinking this through!)

**Comment by tbondwilkinson** [comment]
Are you talking about polyfills here - like how could this new type of routing work in older browsers?

**Comment by mmocny** [comment]
Not so much polyfills as compatibility across the spectrum of use cases.  Again, I don't fully grasp the use cases, but I think if there *are* use cases, it could prevent routers from building on top of the new API wholesale.

I think maybe what I'm asking for is the ability to do something like `<a state=new_state>` instead of `<a href=>` so you can use `navigate`but without updating URL, and without having to fallback to old style click capturing and using history api (because of the complexity and accessibility concerns there).

**Comment by mmocny** [comment]
Also, my ideal outcome here isn't to ask for this complexity if it isn't really needed.  (I don't actually need this support.)

It's just to highlight that we may want to understand that use case, and to understand if won't prevent adoption.
