### ISSUE TITLE
Should `currententrychange` be fired when a document first loads?

### ISSUE THREAD

**Issue by matt-buland-sfdc** [WICG/app-history#30]
If I do a cross-document navigation from A.foo/ to B.foo/ via a URL-bar edit, then document A does not hear `navigate` nor `currententrychange`, but should document B hear a currententrychange? This may be redundant with `load`. What would you expect?

**Comment by domenic** [comment]
Ah, sorry, I was filing my own issue while you were! Let's consolidate over in https://github.com/WICG/app-history/issues/31 :)
