### ISSUE TITLE
What design should be used for reporting navigation duration?

### ISSUE THREAD

**Issue by domenic** [WICG/app-history#33]
After #27, the proposal [discusses](https://github.com/WICG/app-history#current-entry-change-monitoring) how you can get the "duration of the navigation" via `event.timeStamp - event.startTime`, at least for same-document navigations. It has an open question about whether this should work for cross-document navigations (related to #31).

A larger question is whether this property-on-an-event design is the right approach at all. We need to coordinate with the WebPerf folks, e.g. @yoavweiss is apparently [working on](https://docs.google.com/presentation/d/1-gckm8YTJfDnXa_Td8_mWbFDEITtH5CsKOoRKwg4JIM/edit#slide=id.g9c56539c45_0_30) a way to generate `PerformanceEntry` instances for bfcache navigations, which have some similarities to same-document navigations. Maybe (probably?) we should just have same-document navigations be measured via the those performance timeline mechanisms as well.

**Comment by kenchris** [comment]
The @w3ctag think that is makes sense to use the same primitive for this and bfcache navigations, but developers should be able to see what navigation type happened so that you can differentiate the two
