### ISSUE TITLE
What to do about page + iframe history traversal bug in all browsers

### ISSUE THREAD

**Issue by jakearchibald** [WICG/app-history#34]
Right now, if traversing to a history entry means both a parent and iframe need to change history entry, only the parent changes entry, putting the page in a state that doesn't match up to joint session history.

Discussion: https://github.com/whatwg/html/issues/5767#issuecomment-775777376

It seems like this behaviour has been in Firefox since 2002. It might not have been in Chrome as long, but it seems like we couldn't fix it due to compat issues https://github.com/whatwg/html/issues/1191. However, I don't fully understand that bug, and it seems to say things about `about:blank` navigations that aren't true (although, may have been true in 2016).

This bug probably wasn't a big deal because traversals greater than 1 step (either way) aren't all that common. They're a bit hidden in UI, and I don't think `.go()` is used all that often (just guessing).

However, this proposal will result in many traversals greater than 1 step. I'm not sure we'd be able to land this without fixing the bug, or carving out some sort of exception.

**Comment by domenic** [comment]
Having run into this as we implement `goTo()`, I think we have no choice but to fix the bug. We're working on doing that in Chrome and will write tests as we do so and as part of the general history revamp.
