### ISSUE TITLE
push(url, { state, navigateInfo }) is probably nicer than push({ url, state, navigateInfo })

### ISSUE THREAD

**Issue by domenic** [WICG/app-history#39]
In writing examples I'm finding that `appHistory.push({ url: "/foo" })` is kind of annoying. I'd rather write `appHistory.push("/foo")`.

Maybe we should allow both, for cases where the developer only wants to update `state`? Or we could let them explicitly do `push(undefined, { state })` for that case. I'm not sure.

Same for `update()`.

The [callback variants](https://github.com/WICG/app-history#queued-up-single-page-navigations) would continue to return `{ url, state, navigateInfo }` objects, but I don't think the symmetry there is particularly important.

**Comment by tbondwilkinson** [comment]
You could do either - that is, the first argument is either a string or an Object. They're easily typeof differentiable, so no major hassles I think. If it's a string, it's a URL, if it's an Object it must contain url, state, etc.
