### ISSUE TITLE
behavior for update without any parameters

### ISSUE THREAD

**Issue by frehner** [WICG/app-history#52]
Hopefully an easier question: if I'm reading the WebIDL definition correctly, you could potentially call `appHistory.update()` without any parameters, correct? (Also note that the definition for `update` appears to match `push` exactly, and it is explicitly stated that `push` can be called without a parameter)

```
Promise<undefined> update(USVString url, optional AppHistoryEntryOptions options = {});
Promise<undefined> update(optional AppHistoryEntryFullOptions options = {});
Promise<undefined> update(AppHistoryNavigationCallback);
```

In this case, what is the expected behavior of `appHistory.update()` (regarding updates to `url` and/or `state`, as well as event listeners)?

**Comment by domenic** [comment]
Great question. I could swear I disallowed this at one point, but not recently at least...

I think the only sensible option would be for it to do nothing, so probably it's better for it just to throw.

**Comment by domenic** [comment]
Oh, I remember the issue now. Web IDL enforces a rule that any trailing dictionaries with non-required members be marked optional. This works poorly for cases like this, where we want to require "the dictionary must contain at least one value". That has to be specified in prose, not IDL. See https://github.com/heycam/webidl/issues/903.

I'll add a comment to the IDL to remind us of this, and it'll become much clearer when it's fully specced.
