### ISSUE TITLE
Non-goals?

### ISSUE THREAD

**Issue by ericlaw1979** [WICG/app-history#69]
The non-goals section appears to have a list of things that must not be permitted to happen (e.g. see cross-origin URLs). 

Rather than being non-goals, doesn't that mean that each one's opposite should be an explicit Goal?

**Comment by domenic** [comment]
I don't think so? I think "things that are not/must not be supported" are exactly the definition of non-goals?

**Comment by ericlaw1979** [comment]
Okay, if WICG specs lump the "out of scope" and "must nots" together in one section, I guess this should be closed then. Thanks.

**Comment by domenic** [comment]
Yeah, I mean, I think an infinite number of things are out of scope, but the ones that are _interestingly_ out of scope are the ones you might expect to be supported, but instead must not be supported for a good reason.
