### ISSUE TITLE
Consider replacing navigationStartTimeStamp with navigationStart

### ISSUE THREAD

**Issue by esprehn** [WICG/app-history#8]
This would match the performance timing record naming. ex. https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API

**Comment by domenic** [comment]
That makes sense. I thought the symmetry with the `navigationEvent.timeStamp` property would be nice, but I think in general I've been going for too-long names in this API; see also #1.

**Comment by esprehn** [comment]
ah yeah that makes sense, +1 to the shorter names.

**Comment by tbondwilkinson** [comment]
Mark as closed?

**Comment by domenic** [comment]
#27 hasn't been merged yet, and has an outstanding question that I'm hoping to get some insight from experts on... I gotta poke them.

**Comment by domenic** [comment]
Some discussion with @mmocny and @philipwalton revealed that `navigationStart` is basically deprecated. Also, its timeline is not the same as `event.timeStamp`. So, that's not a great name.

I'm going to go temporarily with `startTime`, but there's a larger question about making sure we align with other WebPerf proposals for tracking navigations. Maybe, in the end, we don't even do this via properties of the event object at all, but instead use the performance timeline API. Or maybe we have a PerformanceTimelineEntry as a property of the event. Tricky.

I'll open a new issue to track that larger evolution, and close this one with a renaming to `startTime`.
